---
title: "Homework 2"
author: "Yuan-An Liu A20375099"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
LoadLibraries = function (){
  library(ISLR)
  library(MASS)
  print("The libraries have been loaded .")
}

LoadLibraries()
```
```
Q8.
(a)
i. Yes
ii. strong relationship # not sure
iii. Negative
```
```{r}
lm.fit =lm(mpg~horsepower ,data=Auto)
summary(lm.fit)
```
```
iv.
```
```{r}
# the predicted mpg associated with a horsepower of 98
predict(lm.fit, data.frame(horsepower=c(98)))
# the associated 95% confidence interval
predict(lm.fit, data.frame(horsepower=c(98)), interval = "confidence")
# the associated 95% prediction interval
predict(lm.fit, data.frame(horsepower=c(98)), interval = "prediction")
```
```
(b)
```
```{r echo=FALSE}
attach(Auto) # for plot
plot(horsepower, mpg)
abline(lm.fit)
abline(lm.fit,lwd =3, col ="red")
```
```
(c)
```
```{r echo=FALSE}
plot(lm.fit)
```
```
Q9.
```
```
(a)
```
```{r}
pairs(Auto) # scatterplot matrix
```
```
(b)
```
```{r}
cor(Auto[,1:8]) # correlations between the variables without names
```
```
(c)
```
```{r}
lm.fit =lm(mpg~.-name,data=Auto)
summary(lm.fit)
```
```
i.  Yes
ii. displacement, weight, year and origin
iii. The lower the "year", the higher the "mpg"
```
```
(d)
```
```{r  echo=FALSE}
plot(lm.fit)
```
```
(e)
```
```{r}
Auto2 = Auto[,1:8]
lm2.fit = lm(mpg~.*., data = Auto2)
summary(lm2.fit)
```
```
(f)
```
```{r  echo=FALSE}
attach(Auto)
plot(log(horsepower), mpg)
plot(sqrt(horsepower), mpg)
plot((horsepower)^2, mpg)
```
```
It is a better fit than the original one.
```
```
Q10.
```
```
(a)
```
```{r}
lm.fit =lm(Sales~Price + Urban + US, data = Carseats)
summary(lm.fit)
```
```
(b)
(c)
(e)
```
```{r}
#uses the predictors for which there is evidence of association with the outcome
lm2.fit = lm(Sales~Price + US, data = Carseats)
summary(lm2.fit)
```
```
(f)
```
```{r}
summary(lm.fit)
```
```
Comparing to lm2.fit, the two models are similarly fit.
```
```
(g)
```
```{r}
# Confidence Intervals:
confint(lm2.fit)
```
```
(h)
```
```{r echo=FALSE}
plot(lm2.fit)
```
```
#missing
```
```
Q13.
```
```{r}
set.seed(1)
```
```
set.seed(1) prior to starting part (a): according to the question
```
```
(a)
```
```{r}
x = rnorm(100, 0, 1)
```
```
(b)
```
```{r}
eps = rnorm(100, 0, 0.25)
```
```
(c)
```
```{r}
y = -1 + 0.5*x + eps
length(y)
summary(y)
```
```
length of vector y  = 100 ; beta0 = -1 ; beta1 = 0.5
```
```
(d)
```
```{r echo=FALSE}
plot(x,y)
abline(lm.fit)
```
```
Linear relationship
```
```
(e)
```
```{r}
lm.fit = lm(y~x)
summary(lm.fit)
```
```
beta0 and 1 are similar to the original values
```
```
(f)
```
```{r}
plot(x,y)
abline(lm.fit)
abline (lm.fit ,lwd =3, col ="red")
```
```
(g)
```
```{r}
lm2.fit = lm(y~poly(x, 2))
summary(lm2.fit)
```
```
Regression coefficient of the model is insignificant
```